### ISSUE TITLE
ad tracking - Jaha

### ISSUE THREAD

**Issue by florianap** [florianap/A-First-Look-at-Digital-Security#1]
In Jaha the Student.md we state: "She uses **privacy enhancing browser extensions** to avoid **website visitor tracking** which may reveal some of her interests."

I'm not sure how this matches with this threat model: are we saying that the university could access data at ads companies gathering data on website usage? Shouldn't we just suggest to make sure that she uses HTTPS?

**Comment by mfc** [comment]
it would be good to have privacy enhancing browser extensions somewhere, if not with Jaha. and i agree that having this focus on HTTPS makes sense for Jaha.
