### ISSUE TITLE
"mindful posting" - Jaha

### ISSUE THREAD

**Issue by florianap** [florianap/A-First-Look-at-Digital-Security#2]
This sentence isn't very clear: "Jaha employs mindful posting to ensure what she publishes online cannot be traced back to her (wary of posting locations, specific dates, home addresses, etc.)."

Does this mean that Jaha needs to be mindful about the places and devices where she posts from so as to avoid leaving traces within the university's infrastructure? Or are we talking about anonymizing her postings by switching off geolocation and posting at different times of the day?

**Comment by florianap** [comment]
the same applies for the section on Julio:

"- He remembers what is posted outside of work can hurt the NGO as well. He employs **mindful posting** to ensure what he publishes on his personal accounts cannot be used against him (wary of posting locations, specific dates, home addresses, etc.)."

**Comment by mfc** [comment]
yeah I feel like "mindful posting" should be framed in terms of not sharing unnecessary personal information (geoloc, home addresses, etc), not about anonymity ("cannot be traced back to her"). The wording in Julio's is maybe a little better but still weird as the example doesn't fit the content. 

I would suggest something like:

> "Jaha employs mindful posting to ensure when she posts content online she doesn't accidentally share sensitive personal information she would prefer to be private (her location, home or work addresses, etc.)."

> "He remembers what is posted outside of work can impact the NGO's work as well. He employs mindful posting to ensure what he publishes on his personal accounts cannot be used to personally target him or the NGO he works for (wary of posting locations, images from private events, addresses, etc.)."
