### ISSUE TITLE
Julio - passwords

### ISSUE THREAD

**Issue by florianap** [florianap/A-First-Look-at-Digital-Security#3]
"He has a **password manager** where he generates **unique, strong passwords** with over 30 characters, never using words that can be found in dictionaries, but including numbers and special characters."

- isn't over 30 characters a bit too long?
- if we rule out the possibility of using words that can be found in dictionaries, anyone who bumps into the diceware technique will think it's weak.

**Comment by mfc** [comment]
yeah this is kinda confusing advice. ultimately what we want to suggest is:
1. use diceware for the main memorable password into the password manager, with at minimum four randomly chosen words (so > 20 characters)
2. use password generator within the password manager to create unique passwords with special characters, numbers, etc as long as they can (> 20 characters)
